name: flutter_liquidcore
description: Node.js virtual machine for Android and iOS.

   It basically provides you with a way to execute and evaluate Javascript inside Flutter on Android/iOS.
version: 1.1.1
homepage: https://github.com/j0j00/flutter_liquidcore

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.jojodev.flutter.liquidcore
    pluginClass: LiquidcorePlugin

environment:
  sdk: ">=2.7.0 <3.0.0"
